# Generated by Django 5.2.11 on 2026-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('raster', models.ImageField(upload_to='uploads/', verbose_name='Carte raster')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Carte téléversée',
                'verbose_name_plural': 'Cartes téléversées',
                'ordering': ('-created_at',),
            },
        ),
    ]
