# Generated by Django 5.2.12 on 2026-05-07 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mapupload',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapupload',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapupload',
            name='georef_crs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapupload',
            name='map_name',
            field=models.CharField(blank=True, help_text="Sheet name for auto GCP lookup (e.g. 'tunis', 'ain_bessem')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapupload',
            name='map_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mapupload',
            name='qa_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapupload',
            name='raster_bounds',
            field=models.JSONField(blank=True, help_text='[[lat_sw, lon_sw], [lat_ne, lon_ne]] for Leaflet ImageOverlay', null=True),
        ),
        migrations.AddField(
            model_name='mapupload',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mapupload',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Erreur'),
        ),
        migrations.AlterField(
            model_name='mapupload',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('delete', 'False Positive Removed'), ('edit', 'Boundary Corrected')], max_length=10)),
                ('layer_name', models.CharField(max_length=100)),
                ('feature_id', models.CharField(max_length=200)),
                ('geometry', models.JSONField(blank=True, help_text="New GeoJSON geometry for 'edit'; null for 'delete'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='vectorizer.mapupload')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HITL Correction',
                'verbose_name_plural': 'HITL Corrections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['map_upload', 'layer_name'], name='vectorizer__map_upl_4c8941_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_image', models.ImageField(upload_to='patches/images/')),
                ('mask_image', models.ImageField(blank=True, null=True, upload_to='patches/masks/')),
                ('tile_row', models.PositiveIntegerField()),
                ('tile_col', models.PositiveIntegerField()),
                ('crop_x', models.PositiveIntegerField()),
                ('crop_y', models.PositiveIntegerField()),
                ('layer_name', models.CharField(max_length=100)),
                ('patch_status', models.CharField(choices=[('raw', 'Extrait'), ('corrected', 'Corrigé'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='raw', max_length=20)),
                ('correction_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_patches', to='vectorizer.mapupload')),
            ],
            options={
                'verbose_name': 'Training Patch',
                'verbose_name_plural': 'Training Patches',
                'ordering': ['map_upload', 'layer_name', 'tile_row', 'tile_col'],
                'unique_together': {('map_upload', 'layer_name', 'tile_row', 'tile_col')},
            },
        ),
    ]
