# Generated by Django 5.2.12 on 2026-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorizer', '0004_mapupload_has_georeference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='no_synthetic',
            field=models.BooleanField(default=False, help_text='SEMAP only : exclut les 12 122 images synthétiques.'),
        ),
    ]
